 
name: Build Pyinstaller

on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    tags:
      - "*"
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  check-the-ref:
    runs-on: ubuntu-latest
    steps:
      - name: check the ref
        run : echo ${{github.ref}}

  release:
    runs-on: ${{ matrix.os }}
    # if: ${{ startsWith('refs/tags/v', github.ref) }}
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name : Install python
        uses: actions/setup-python@v2.2.2
        with:
          python-version: '3.x'
      - name: Install dependencies
        run : pip install -r requirements.txt

      - name: run build.py
        run : python build.py

      - name : Release
        uses: ncipollo/release-action@v1
        env:
          token: ${{ secrets.GITHUB_TOKEN }}
          draft: true
          artifacts : "dist/*"
          tag : "latest"




      # - name: Build/release Electron app