 
name: Build Pyinstaller

on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    tags:
      - "*"
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    # if: ${{ startsWith('refs/tags/v', github.ref) }}
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Package Application
        uses: JackMcKew/pyinstaller-action-windows@main
        with:
          path : .

      - name : Release
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          draft: true
          artifacts : "dist/windows/*"
          tag : "latest"




      # - name: Build/release Electron app